"""
Tests for POST /predict.

Regression assertions load tests/fixtures/smoke_test_transactions.json,
which is generated by scripts/capture_smoke_tests.py directly against the
real loaded pipeline - not hand-reconstructed or remembered from a
notebook. If that fixture is missing, the fixture-based tests below are
skipped with an explicit instruction rather than failing opaquely, since a
missing fixture means "capture script hasn't been run yet," not "the
service is broken."
"""

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "smoke_test_transactions.json"


def _load_fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"{FIXTURE_PATH} not found. Run `python scripts/capture_smoke_tests.py` "
            "once against the real loaded pipeline to generate it, then re-run tests."
        )
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def _fixture_cases() -> list[dict]:
    """Loaded eagerly at collection time so pytest.mark.parametrize can use it."""
    if not FIXTURE_PATH.exists():
        return []
    with open(FIXTURE_PATH) as f:
        return json.load(f)["cases"]


@pytest.mark.parametrize(
    "case",
    _fixture_cases(),
    ids=lambda case: case["label"] if isinstance(case, dict) else "no-fixture",
)
def test_predict_matches_captured_smoke_test(client: TestClient, case: dict) -> None:
    """
    Each case here has a genuinely verified input->output pairing, captured
    directly from the real pipeline by scripts/capture_smoke_tests.py. If
    any of these ever fail, do not adjust expected values to make them
    pass - it means the deployed model artifact or feature engineering has
    changed. Investigate and, if the change is intentional (e.g. a new
    trained model version), re-run the capture script deliberately and
    review the diff.
    """
    response = client.post("/predict", json=case["input"])
    assert response.status_code == 200

    body = response.json()
    assert body["prediction"] == case["expected_prediction"]
    assert body["fraud_probability"] == pytest.approx(case["expected_fraud_probability"], rel=1e-6)
    assert body["model_version"]
    # Contract enforcement: exactly these three fields, nothing else.
    assert set(body.keys()) == {"prediction", "fraud_probability", "model_version"}


def test_fixture_exists_and_is_non_empty() -> None:
    """
    An explicit, readable failure if the fixture was never generated - the
    parametrized test above would otherwise just silently collect zero
    cases and appear to "pass" with nothing actually tested.
    """
    fixture = _load_fixture()
    assert len(fixture["cases"]) > 0, "Fixture exists but contains no cases - re-run the capture script."


def test_predict_rejects_invalid_transaction_type(client: TestClient) -> None:
    payload = {
        "step": 1,
        "type": "NOT_A_REAL_TYPE",
        "amount": 181,
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    assert response.status_code == 422
    body = response.json()
    assert body["error"] == "validation_error"


def test_predict_rejects_negative_amount(client: TestClient) -> None:
    payload = {
        "step": 1,
        "type": "TRANSFER",
        "amount": -50,
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    assert response.status_code == 422


def test_predict_rejects_zero_amount(client: TestClient) -> None:
    payload = {
        "step": 1,
        "type": "TRANSFER",
        "amount": 0,
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    assert response.status_code == 422


def test_predict_rejects_missing_required_field(client: TestClient) -> None:
    payload = {
        "step": 1,
        "type": "TRANSFER",
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    assert response.status_code == 422


def test_predict_rejects_zero_step(client: TestClient) -> None:
    payload = {
        "step": 0,
        "type": "TRANSFER",
        "amount": 181,
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    assert response.status_code == 422


def test_predict_response_does_not_leak_engineered_features_or_derived_values(client: TestClient) -> None:
    """
    origBalanceDiff / destBalanceDiff are internal computation details, and
    confidence / risk_level are Spring Boot's responsibility per the frozen
    contract - none of these must ever appear in this service's response.
    """
    payload = {
        "step": 1,
        "type": "TRANSFER",
        "amount": 181,
        "oldbalanceOrg": 181,
        "newbalanceOrig": 0,
        "oldbalanceDest": 0,
        "newbalanceDest": 0,
    }
    response = client.post("/predict", json=payload)
    body = response.json()
    assert "origBalanceDiff" not in body
    assert "destBalanceDiff" not in body
    assert "confidence" not in body
    assert "risk_level" not in body
