import {
  ArrowLeftRight,
  ShieldAlert,
  Radar,
  Activity,
  RefreshCw,
} from "lucide-react";

import StatCard from "../../components/ui/StatCard";
import RiskDistributionChart from "../../components/dashboard/RiskDistributionChart";
import TransactionTrendChart from "../../components/dashboard/TransactionTrendChart";
import RecentTransactionsTable from "../../components/dashboard/RecentTransactionsTable";
import RecentPredictionsTable from "../../components/dashboard/RecentPredictionsTable";
import OpenAlertsPanel from "../../components/dashboard/OpenAlertsPanel";

import { useDashboard } from "../../hooks/useDashboard";
import { useAuth } from "../../context/AuthContext";

export default function AdminDashboard() {
  const { user } = useAuth();

  const {
    isLoading,
    isRefreshing,
    stats,
    trendData,
    recentPredictions,
    recentTransactions,
    alerts,
    refetch,
  } = useDashboard(user?.userId, user?.role);

  function handleAlertClosed() {
    refetch();
  }

  return (
    <div className="mx-auto max-w-7xl px-6 py-8">
      {/* Header */}
      <div className="mb-7 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="font-display text-3xl font-semibold text-ink">
            Fraud Monitoring Dashboard
          </h1>

          <p className="mt-1 text-sm text-slate-500">
            Monitor transactions, predictions and fraud alerts across the
            platform.
          </p>
        </div>

        <div className="flex items-center gap-1.5 text-xs text-slate-400">
          <RefreshCw size={12} className={isRefreshing ? "animate-spin" : ""} />
          {isRefreshing ? "Refreshing..." : "Auto refresh every 30 seconds"}
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="Transactions Analysed"
          value={stats.totalTransactions}
          icon={ArrowLeftRight}
          tone="neutral"
          caption="Processed transactions"
          trend={stats.totalTransactionsTrend}
          isLoading={isLoading}
        />

        <StatCard
          label="Fraud Predictions"
          value={stats.totalPredictions}
          icon={Radar}
          tone="neutral"
          caption="Generated by ML model"
          isLoading={isLoading}
        />

        <StatCard
          label="Open Alerts"
          value={stats.openAlertsCount}
          icon={ShieldAlert}
          tone={stats.openAlertsCount > 0 ? "danger" : "good"}
          caption="Require analyst review"
          isLoading={isLoading}
        />

        <StatCard
          label="High Risk Cases"
          value={stats.highRiskCount}
          icon={Activity}
          tone={stats.highRiskCount > 0 ? "warning" : "good"}
          caption="Detected in current dataset"
          isLoading={isLoading}
        />
      </div>

      {/* Charts */}
      <div className="mt-6 grid grid-cols-1 gap-5 lg:grid-cols-2">
        <TransactionTrendChart trendData={trendData} isLoading={isLoading} />

        <RiskDistributionChart
          predictions={recentPredictions}
          isLoading={isLoading}
        />
      </div>

      {/* Recent Transactions */}
      <div className="mt-6">
        <RecentTransactionsTable
          rows={recentTransactions}
          isLoading={isLoading}
        />
      </div>

      {/* Recent Predictions */}
      <div className="mt-6">
        <RecentPredictionsTable
          predictions={recentPredictions}
          isLoading={isLoading}
        />
      </div>

      {/* Open Alerts */}
      <div className="mt-6">
        <OpenAlertsPanel
          alerts={alerts}
          isLoading={isLoading}
          onAlertClosed={handleAlertClosed}
        />
      </div>
    </div>
  );
}
